// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP3AppWeb.Models;

#nullable disable

namespace TP3AppWeb.Migrations
{
    [DbContext(typeof(TP3Context))]
    partial class TP3ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JeuUtilisateur", b =>
                {
                    b.Property<int>("FavorisEvaluationID")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateursUtilisateurID")
                        .HasColumnType("int");

                    b.HasKey("FavorisEvaluationID", "UtilisateursUtilisateurID");

                    b.HasIndex("UtilisateursUtilisateurID");

                    b.ToTable("JeuUtilisateur");

                    b.HasData(
                        new
                        {
                            FavorisEvaluationID = 10,
                            UtilisateursUtilisateurID = 1
                        },
                        new
                        {
                            FavorisEvaluationID = 2,
                            UtilisateursUtilisateurID = 1
                        },
                        new
                        {
                            FavorisEvaluationID = 8,
                            UtilisateursUtilisateurID = 1
                        },
                        new
                        {
                            FavorisEvaluationID = 10,
                            UtilisateursUtilisateurID = 2
                        },
                        new
                        {
                            FavorisEvaluationID = 3,
                            UtilisateursUtilisateurID = 2
                        },
                        new
                        {
                            FavorisEvaluationID = 1,
                            UtilisateursUtilisateurID = 2
                        },
                        new
                        {
                            FavorisEvaluationID = 4,
                            UtilisateursUtilisateurID = 3
                        },
                        new
                        {
                            FavorisEvaluationID = 1,
                            UtilisateursUtilisateurID = 3
                        },
                        new
                        {
                            FavorisEvaluationID = 6,
                            UtilisateursUtilisateurID = 3
                        });
                });

            modelBuilder.Entity("TP3AppWeb.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationID")
                        .HasColumnType("int");

                    b.Property<int>("Cote")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvaluationID");

                    b.ToTable("Evaluation", (string)null);

                    b.HasData(
                        new
                        {
                            EvaluationID = 1,
                            Cote = 5,
                            Description = "Hogwarts Legacy : L'Héritage de Poudlard est un RPG d'action-aventure immersif en monde ouvert. Vous pouvez prendre le contrôle et vous retrouver au centre de votre propre aventure dans le Monde des sorciers."
                        },
                        new
                        {
                            EvaluationID = 2,
                            Cote = 4,
                            Description = "Le shooter-looter est de retour avec ses trilliards de flingues pour une aventure complètement folle ! Affrontez de nouveaux mondes et ennemis dans la peau de l'un des quatre Chasseurs de l'Arche proposés, avec chacun ses propres compétences et options de personnalisation."
                        },
                        new
                        {
                            EvaluationID = 3,
                            Cote = 5,
                            Description = "Vous avez hérité de l’ancienne parcelle de ferme de votre grand-père à Stardew Valley. Armé d’outils à la main et de quelques pièces de monnaie, vous avez entrepris de commencer votre nouvelle vie. Pouvez-vous apprendre à vivre de la terre et à transformer ces champs envahis par la végétation en une habitation prospère?"
                        },
                        new
                        {
                            EvaluationID = 4,
                            Cote = 5,
                            Description = "Un jeu multijoueur brutal d'exploration et de survie pour 1 à 10 joueurs, prenant place dans un purgatoire en génération procédurale inspiré par la culture viking. Combattez, bâtissez et accomplissez des exploits à la gloire d'Odin!"
                        },
                        new
                        {
                            EvaluationID = 5,
                            Cote = 4,
                            Description = "Dans un monde dystopique aussi déjanté que sublime, armez-vous de votre gant de pouvoirs, de votre arsenal d’armes blanches et de votre artillerie à la pointe de la technologie, et lancez-vous dans des affrontements explosifs et mortellement nerveux."
                        },
                        new
                        {
                            EvaluationID = 6,
                            Cote = 4,
                            Description = "BRISEZ LE CYCLE Combattez pour votre survie dans ce jeu de tir à la troisième personne récompensé qui apporte l'histoire de Selene. Affrontez les défis du genre roguelike. Faites face à vos ennemis dans un déluge de balles. Voyagez dans Returnal™ avec un autre joueur."
                        },
                        new
                        {
                            EvaluationID = 7,
                            Cote = 4,
                            Description = "Civilization VI est le dernier épisode de la franchise éponyme, récompensée de nombreuses fois. Repoussez les frontières de votre empire, développez votre patrimoine culturel et affrontez les plus grands seigneurs de l'histoire. Votre civilisation tiendra-t-elle face aux ravages du temps ?"
                        },
                        new
                        {
                            EvaluationID = 8,
                            Cote = 2,
                            Description = "Soyez à la hauteur de ce qu’on attend de vous dans NBA 2K23. Le mode scénario permet de suivre votre joueur, qui sera surnommé MP, tout au long de sa carrière de basketball."
                        },
                        new
                        {
                            EvaluationID = 9,
                            Cote = 4,
                            Description = "Grand Theft Auto V offre aux joueurs la possibilité d'explorer le monde de Los Santos et Blaine County et ses crimes."
                        },
                        new
                        {
                            EvaluationID = 10,
                            Cote = 5,
                            Description = "Survie et épouvante atteignent des sommets dans le 8e titre de la franchise Resident Evil : Resident Evil Village. Graphismes ultra-détaillés, action intense en vue subjective et récit palpitant : la peur n'a jamais été aussi palpable."
                        });
                });

            modelBuilder.Entity("TP3AppWeb.Models.Jeu", b =>
                {
                    b.Property<int>("EvaluationID")
                        .HasColumnType("int");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateProduction")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extrait")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JeuID")
                        .HasColumnType("int");

                    b.Property<string>("NomDuJeu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeDeJeu")
                        .HasColumnType("int");

                    b.HasKey("EvaluationID");

                    b.ToTable("Jeu", (string)null);

                    b.HasData(
                        new
                        {
                            EvaluationID = 1,
                            Auteur = "Warner Bros. Games",
                            Complet = "https://store.steampowered.com/app/990080/Hogwarts_Legacy_LHritage_de_Poudlard/?l=french",
                            DateProduction = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duree = "Environ 35 heures",
                            Extrait = "https://www.youtube.com/embed/M8ApyJqnME0",
                            Image = "https://w0.peakpx.com/wallpaper/461/931/HD-wallpaper-hogwarts-legacy-poster.jpg",
                            JeuID = 1,
                            NomDuJeu = "Hogwarts Legacy : L'Héritage de Poudlard",
                            Producteur = "Avalanche Software",
                            TypeDeJeu = 0
                        },
                        new
                        {
                            EvaluationID = 2,
                            Auteur = "2K",
                            Complet = "https://store.steampowered.com/app/397540/Borderlands_3/",
                            DateProduction = new DateTime(2020, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duree = "Environ 35 heures",
                            Extrait = "https://www.youtube.com/embed/zW8rXQnKirE",
                            Image = "https://images5.alphacoders.com/100/thumb-1920-1004495.jpg",
                            JeuID = 2,
                            NomDuJeu = "Borderlands 3",
                            Producteur = "Gearbox Software",
                            TypeDeJeu = 1
                        },
                        new
                        {
                            EvaluationID = 3,
                            Auteur = "ConcernedApe",
                            Complet = "https://store.steampowered.com/app/413150/Stardew_Valley/",
                            DateProduction = new DateTime(2016, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duree = "Environ 52 heures",
                            Extrait = "https://www.youtube.com/embed/ot7uXNQskhs",
                            Image = "https://www.researchgate.net/publication/342704239/figure/fig1/AS:960471637192707@1606005691630/Stardew-Valley-promotional-image-Sourcewwwstardewvalleynet-Image-copyright-Eric-Barone.jpg",
                            JeuID = 3,
                            NomDuJeu = "Stardew Valley",
                            Producteur = "ConcernedApe",
                            TypeDeJeu = 2
                        },
                        new
                        {
                            EvaluationID = 4,
                            Auteur = "Coffee Stain Publishing",
                            Complet = "https://store.steampowered.com/app/892970/Valheim/",
                            DateProduction = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duree = "Environ 75 heures",
                            Extrait = "https://www.youtube.com/embed/liQLtCLq3tc",
                            Image = "https://preview.redd.it/cb6vhjj30ap61.gif?format=png8&s=7fede5f0fb30bd3aa14dfdb16eb56e8e8412dedc",
                            JeuID = 4,
                            NomDuJeu = "Valheim",
                            Producteur = "Iron Gate AB",
                            TypeDeJeu = 3
                        },
                        new
                        {
                            EvaluationID = 5,
                            Auteur = "Focus Entertainment",
                            Complet = "https://store.steampowered.com/app/668580/Atomic_Heart/",
                            DateProduction = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duree = "Environ 25 heures",
                            Extrait = "https://www.youtube.com/embed/h8F4hnR1FoE",
                            Image = "https://news.xbox.com/en-us/wp-content/uploads/sites/2/2022/12/ATOMIC-_HEART_Store_Featured_JPG-af8c6994d37e4bfb590d.jpg",
                            JeuID = 5,
                            NomDuJeu = "Atomic Heart",
                            Producteur = "Mundfish",
                            TypeDeJeu = 4
                        },
                        new
                        {
                            EvaluationID = 6,
                            Auteur = "PlayStation PC LLC",
                            Complet = "https://store.steampowered.com/app/1649240/Returnal/",
                            DateProduction = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duree = "Environ 19 heures",
                            Extrait = "https://www.youtube.com/embed/BcnRCjHViLw",
                            Image = "https://images.alphacoders.com/113/thumb-1920-1137684.jpg",
                            JeuID = 6,
                            NomDuJeu = "Returnal",
                            Producteur = "Housemarque",
                            TypeDeJeu = 5
                        },
                        new
                        {
                            EvaluationID = 7,
                            Auteur = "2K",
                            Complet = "https://store.steampowered.com/app/289070/Sid_Meiers_Civilization_VI/",
                            DateProduction = new DateTime(2016, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duree = "Environ 22 heures",
                            Extrait = "https://www.youtube.com/embed/5KdE0p2joJw",
                            Image = "https://i0.wp.com/mynintendonews.com/wp-content/uploads/2018/09/civilization_vi.jpg?fit=1500%2C1000&ssl=1",
                            JeuID = 7,
                            NomDuJeu = "Sid Meier’s Civilization VI",
                            Producteur = "Firaxis Games",
                            TypeDeJeu = 6
                        },
                        new
                        {
                            EvaluationID = 8,
                            Auteur = "2K",
                            Complet = "https://store.steampowered.com/app/1919590/NBA_2K23/",
                            DateProduction = new DateTime(2022, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duree = "Environ 12 heures",
                            Extrait = "https://www.youtube.com/embed/vE_oLyx25IU",
                            Image = "https://nba2kw.com/wp-content/uploads/2022/06/nba-2k23-cover-athlete-devin-booker-standard-edition.jpg",
                            JeuID = 8,
                            NomDuJeu = "NBA 2K23",
                            Producteur = "Visual Concepts",
                            TypeDeJeu = 7
                        },
                        new
                        {
                            EvaluationID = 9,
                            Auteur = "Rockstar Games",
                            Complet = "https://store.steampowered.com/app/271590/Grand_Theft_Auto_V/",
                            DateProduction = new DateTime(2015, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duree = "Environ 31 heures",
                            Extrait = "https://www.youtube.com/embed/0hNYgYXhWkM",
                            Image = "https://media.rockstargames.com/rockstargames/img/global/news/upload/actual_1364906194.jpg",
                            JeuID = 9,
                            NomDuJeu = "Grand Theft Auto V",
                            Producteur = "Rockstar North",
                            TypeDeJeu = 8
                        },
                        new
                        {
                            EvaluationID = 10,
                            Auteur = "CAPCOM Co., Ltd.",
                            Complet = "https://store.steampowered.com/app/1196590/Resident_Evil_Village/",
                            DateProduction = new DateTime(2021, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duree = "Environ 9 heures",
                            Extrait = "https://www.youtube.com/embed/tjfTxFzGh3Q",
                            Image = "https://www.residentevil.com/village/assets/images/common/share.png",
                            JeuID = 10,
                            NomDuJeu = "Resident Evil Village",
                            Producteur = "CAPCOM Co., Ltd.",
                            TypeDeJeu = 4
                        });
                });

            modelBuilder.Entity("TP3AppWeb.Models.Utilisateur", b =>
                {
                    b.Property<int>("UtilisateurID")
                        .HasColumnType("int");

                    b.Property<string>("IdentifiantUnique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UtilisateurID");

                    b.ToTable("Utilisateur", (string)null);

                    b.HasData(
                        new
                        {
                            UtilisateurID = 1,
                            IdentifiantUnique = "bob123",
                            MotDePasse = "secret",
                            Nom = "Bobob",
                            Prenom = "Bob",
                            Pseudo = "Bobby",
                            Role = 2
                        },
                        new
                        {
                            UtilisateurID = 2,
                            IdentifiantUnique = "gerry321",
                            MotDePasse = "mdp123",
                            Nom = "Tremblay",
                            Prenom = "George",
                            Pseudo = "Muffin",
                            Role = 1
                        },
                        new
                        {
                            UtilisateurID = 3,
                            IdentifiantUnique = "joejoe546",
                            MotDePasse = "Soleil01",
                            Nom = "Jean",
                            Prenom = "Joe",
                            Pseudo = "Joejoe",
                            Role = 1
                        });
                });

            modelBuilder.Entity("JeuUtilisateur", b =>
                {
                    b.HasOne("TP3AppWeb.Models.Jeu", null)
                        .WithMany()
                        .HasForeignKey("FavorisEvaluationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP3AppWeb.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UtilisateursUtilisateurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TP3AppWeb.Models.Jeu", b =>
                {
                    b.HasOne("TP3AppWeb.Models.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });
#pragma warning restore 612, 618
        }
    }
}
